services:
    #PHP MAIN APP
    php:
        build:
            context: .
            target: php
            args: 
                - APP_ENV=${APP_ENV}
        container_name: expense-main-app
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app   
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        ports:
            - "8000:8000"
        depends_on:
            - database

    #NODEJS
    node:
        build:
            context: .
            target: node
        container_name: expense-node
        volumes:
            - .:/usr/src/app
            - ./node_modules:/usr/src/app/node_modules
        tty: true
        ports:
            - "5173:5173"

    #DATABASE
    database:
        image: mysql@sha256:569c4128dfa625ac2ac62cdd8af588a3a6a60a049d1a8d8f0fac95880ecdbbe5
        ports:
            - "3306:3306"
        container_name: expense-mysql
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - expense-tracker-data:/var/lib/mysql


volumes:
    expense-tracker-data: